language: java
jdk: openjdk11
sudo: true

script:
  - cd buildinggame
  - mvn clean install -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -D maven.wagon.http.ssl.insecure=true -D maven.wagon.http.ssl.allowall=true