main: com.gmail.stefvanschiedev.buildinggame.Main
version: 6.0.0
name: BuildingGame
author: stefvanschie
softdepend: [Vault, Socket4MC, LeaderHeads, PerWorldInventory, PlaceholderAPI, WorldEdit]

api-version: 1.13