main: com.gmail.stefvanschiedev.buildinggame.Main
version: 8.0.2
name: BuildingGame
author: stefvanschie
softdepend: [Vault, PerWorldInventory, PlaceholderAPI, WorldEdit, MVdWPlaceholderAPI, HolographicDisplays, Citizens]

api-version: 1.13