main: com.gmail.stefvanschiedev.buildinggame.Main
version: 7.1.0
name: BuildingGame
author: stefvanschie
softdepend: [Vault, PerWorldInventory, PlaceholderAPI, WorldEdit, MVdWPlaceholderAPI, HolographicDisplays, Citizens]

api-version: 1.13