main: com.gmail.stefvanschiedev.buildinggame.Main
version: 6.1.0
name: BuildingGame
author: stefvanschie
softdepend: [Vault, Socket4MC, LeaderHeads, PerWorldInventory, PlaceholderAPI, WorldEdit, MVdWPlaceholderAPI, HolographicDisplays]

api-version: 1.13