main: com.gmail.stefvanschiedev.buildinggame.Main
version: 6.3.0
name: BuildingGame
author: stefvanschie
softdepend: [Vault, LeaderHeads, PerWorldInventory, PlaceholderAPI, WorldEdit, MVdWPlaceholderAPI, HolographicDisplays]

api-version: 1.13