main: com.gmail.stefvanschiedev.buildinggame.Main
version: 3.0.1
name: BuildingGame
author: stefvanschie
softdepend: [Vault, SocketAPI]

commands:
  bg:
    description: Main buildinggame command
  buildinggame:
    description: Main buildinggame command