main: com.gmail.stefvanschiedev.buildinggame.Main
version: 5.4.3
name: BuildingGame
author: stefvanschie
softdepend: [Vault, Socket4MC, LeaderHeads, PerWorldInventory, PlaceholderAPI]

commands:
  bg:
    description: Main buildinggame command
  buildinggame:
    description: Main buildinggame command