name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:
  build-bg:
    name: 'Build Building Game'
    runs-on: ubuntu-latest
    steps:
    - name: Cache jars
      id: cache-jars
      uses: actions/cache@v2
      with:
        path: |
          .paper-nms
          build
          paperclip
          ~/.m2/repository/io/papermc/paper
          ~/.m2/repository/ca/bkaw/paper-nms
          ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-jars
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run paper-nms init
      if: steps.cache-jars.outputs.cache-hit != 'true'
      run: |
        cd buildinggame
        mvn paper-nms:init -pl nms/1_19_0
        mvn paper-nms:init -pl nms/1_19_1
        mvn paper-nms:init -pl nms/1_19_2
        mvn paper-nms:init -pl nms/1_19_3
        mvn paper-nms:init -pl nms/1_19_4
        mvn paper-nms:init -pl nms/1_20_0-1
        mvn paper-nms:init -pl nms/1_20_2
        mvn paper-nms:init -pl nms/1_20_3
        mvn paper-nms:init -pl nms/1_20_4
    - name: Run BuildTools
      if: steps.cache-jars.outputs.cache-hit != 'true'
      run: |
        mkdir -p build
        cd build/
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        
        git clone https://hub.spigotmc.org/stash/scm/spigot/bukkit.git Bukkit
        cd Bukkit
        git checkout 304e83eb384c338546aa96eea51388e0e8407e26
        cd ..
        
        git clone https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git CraftBukkit
        cd CraftBukkit
        git checkout 91b1fc3f1cf89e2591367dca1fa7362fe376f289
        cd ..
        
        git clone https://hub.spigotmc.org/stash/scm/spigot/spigot.git Spigot
        cd Spigot
        git checkout b698b49caf14f97a717afd67e13fd7ac59f51089
        cd ..
        
        git clone https://hub.spigotmc.org/stash/scm/spigot/builddata.git BuildData
        cd BuildData
        git checkout a7f7c2118b877fde4cf0f32f1f730ffcdee8e9ee
        cd ..
        
        java -jar BuildTools.jar --remapped --disable-java-check --dont-update
        
        java -jar BuildTools.jar --rev 1.20.6 --remapped --disable-java-check
        java -jar BuildTools.jar --rev 1.21.1 --remapped --disable-java-check
        java -jar BuildTools.jar --rev 1.21.3 --remapped --disable-java-check
        
        cd ../
    - name: Build with Maven
      run: |
        cd buildinggame
        mvn -B package --file pom.xml
  build-addon:
    name: 'Build Addon'
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build with Maven
      run: |
        cd addon
        mvn -B package --file pom.xml
  build-bungeecord:
    name: 'Build BungeeCord'
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build with Maven
      run: |
        cd bungeecord
        mvn -B package --file pom.xml
